title: qty cinema
baseurl: "/"

permalink: /:categories/:year/:month/:day/:title/

collections:
  movies:
    output: true
    permalink: /:name

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

timezone: America/Toronto

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "content"

# Build settings
plugins:
  - jekyll-feed
sass:
    sass_dir: _sass

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/