title: qty cinema
baseurl: "/qty"

permalink: /:categories/:year/:month/:day/:title

collections:
  - authors:
      output: true
  - movies:
      output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "content"