backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "assets/uploads" # Media files will be stored in the repo under assets/images/uploads
public_folder: "assets/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "authors" # Used in routes, e.g., /admin/collections/blog
    label: "Authors" # Used in the UI
    folder: "_authors/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Display Name", name: "short_name", widget: "string"}
      - {label: "Full Name", name: "name", widget: "string"}
  - name: "posts"
    label: "Posts"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'publish_date', widget: 'datetime' }
      - {
        label: 'Author',
        name: 'author',
        widget: 'relation',
        collection: 'authors',
        display_fields: [display_name],
        search_fields: [display_name],
        value_field: 'name',
      }
      - { label: 'Body', name: 'body', widget: 'markdown' }