backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "assets/uploads" # Media files will be stored in the repo under assets/images/uploads
public_folder: "assets/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'About Page'
        name: 'about'
        file: 'about.md'
        fields:
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'content' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: "authors" # Used in routes, e.g., /admin/collections/blog
    label: "Authors" # Used in the UI
    folder: "_authors/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Display Name", name: "short_name", widget: "string"}
      - {label: "Full Name", name: "name", widget: "string"}
  - name: "posts"
    label: "Posts"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'publish_date', widget: 'datetime' }
      - {
        label: 'Author',
        name: 'author',
        widget: 'relation',
        collection: 'authors',
        display_fields: [short_name],
        search_fields: [short_name],
        value_field: 'name',
      }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: "movies"
    label: "Movies"
    folder: "_movies/"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "movie"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Director", name: "director", widget: "string"}
      - {label: "Link", name: "link", widget: "hidden", default: true}
      - {label: "Watch Link", name: "watch", widget: "string", required: false, pattern: ['http:\/\/[\w\d]+\.[\w\d]+\.?[\w\d]*\/?.*', 'Must be a valid URL (begins with http://)']}
      - {label: "Short description", name: "synopsis", widget: "string", required: false}
      - {label: "Main Image", name: "image", widget: "image", allow_multiple: false}